INSERT INTO INGREDIENTS (NAME) VALUES ('Harina');
INSERT INTO INGREDIENTS (NAME) VALUES ('Azúcar');
INSERT INTO INGREDIENTS (NAME) VALUES ('Huevos');
INSERT INTO INGREDIENTS (NAME) VALUES ('Manteca');
INSERT INTO INGREDIENTS (NAME) VALUES ('Leche');
INSERT INTO INGREDIENTS (NAME) VALUES ('Sal');
INSERT INTO INGREDIENTS (NAME) VALUES ('Aceite');
INSERT INTO INGREDIENTS (NAME) VALUES ('Pollo');
INSERT INTO INGREDIENTS (NAME) VALUES ('Tomate');
INSERT INTO INGREDIENTS (NAME) VALUES ('Queso');
INSERT INTO INGREDIENTS (NAME) VALUES ('Carne Roja');
INSERT INTO INGREDIENTS (NAME) VALUES ('Mantequilla');

