INSERT INTO INGREDIENTS (NAME) VALUES ('Harina');
INSERT INTO INGREDIENTS (NAME) VALUES ('Azúcar');
INSERT INTO INGREDIENTS (NAME) VALUES ('Huevos');
INSERT INTO INGREDIENTS (NAME) VALUES ('Manteca');
INSERT INTO INGREDIENTS (NAME) VALUES ('Leche');
INSERT INTO INGREDIENTS (NAME) VALUES ('Sal');
INSERT INTO INGREDIENTS (NAME) VALUES ('Aceite');
INSERT INTO INGREDIENTS (NAME) VALUES ('Pollo');
INSERT INTO INGREDIENTS (NAME) VALUES ('Tomate');
INSERT INTO INGREDIENTS (NAME) VALUES ('Queso');
INSERT INTO INGREDIENTS (NAME) VALUES ('Carne Roja');
INSERT INTO INGREDIENTS (NAME) VALUES ('Mantequilla');

INSERT INTO ROLES (NAME,DESCRIPTION) VALUES ('ADMIN','Permite acceso a todos los recursos')
INSERT INTO USERS (USERNAME, PASSWORD, ACTIVE) VALUES ('ADMIN', '$2a$10$MjuAK6HyKzjPn95Rab.CKuBC0vC5EtKA17odhYucfJhkR2yq9drmK', 1);
INSERT INTO USERS_ROLE (USER_ID,ROLE_ID) VALUES (1,1)
